In [5]:
import pandas as pd
import numpy as np
import pyshark
import asyncio
import ssl

DATA_FOLDER = "data"
PCAP_FILE = f"{DATA_FOLDER}/mom_3.pcap"
TOP_URLS_FILE = f"{DATA_FOLDER}/top_urls.csv"

OUTPUT_FOLDER = f"output"
OUTPUT_FILE = f"{OUTPUT_FOLDER}/mom_3.csv"

In [6]:
top_urls = pd.read_csv(TOP_URLS_FILE)
https_urls = top_urls[top_urls["url"].str.startswith("https://")]
https_urls

                            url
2           https://18comic.vip
3         https://7games.bet.br
4         https://8moviesda.net
5           https://9animetv.to
6         https://9moviesda.com
..                          ...
995           https://zbporn.tv
996   https://zeenews.india.com
997  https://zh.m.wikipedia.org
998         https://zonatmo.com
999             https://zozo.jp

[998 rows x 1 columns]

In [7]:
context = ssl.create_default_context()
i = 1


async def good_url(url):
    domain = url.removeprefix("https://")
    try:
        _, writer = await asyncio.wait_for(asyncio.open_connection(domain, 443), timeout=25)
        await writer.start_tls(
            context, server_hostname=domain, ssl_handshake_timeout=5, ssl_shutdown_timeout=5
        )

        global i
        if i % 50 == 0:
            print(f"{i} good URLs so far...")
        i += 1

        return True
    except Exception as e:
        if str(e):
            print(f"Error connecting {domain}: {e}")
        else:
            print(f"Error connecting {domain}: {repr(e)}")
        return False


good_urls_indices = await asyncio.gather(*[good_url(url) for url in https_urls["url"].tolist()])
good_urls = https_urls[good_urls_indices]

Error connecting cdn.qaliy.com: [Errno 104] Connection reset by peer
50 good URLs so far...
100 good URLs so far...
Error connecting cricbet99.club: [Errno -5] No address associated with hostname
Error connecting cdn.gd85.com: [Errno 104] Connection reset by peer
Error connecting googll.store: [Errno 104] Connection reset by peer
150 good URLs so far...
200 good URLs so far...
Error connecting m.nkryu17dc.com: [Errno -3] Temporary failure in name resolution
Error connecting hrms.indianrail.gov.in: [Errno 111] Connect call failed ('203.176.112.88', 443)
Error connecting bollyflix.tw: [Errno -2] Name or service not known
Error connecting mangabuff.ru: [Errno 104] Connection reset by peer
250 good URLs so far...
Error connecting gall.dcinside.com: SSL handshake is taking longer than 5 seconds: aborting the connection
Error connecting moviebox.ng: [Errno -2] Name or service not known
Error connecting moviesda.it.com: [Errno -5] No address associated with hostname
Error connecting m.dcinside.com: SSL handshake is taking longer than 5 seconds: aborting the connection
300 good URLs so far...
Error connecting phe18.vip: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1032)
350 good URLs so far...
Error connecting service.smt.docomo.ne.jp: [SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED] unsafe legacy renegotiation disabled (_ssl.c:1032)
Error connecting mnregaweb4.nic.in: [Errno 104] Connection reset by peer
Error connecting streamable.cloud: [Errno -2] Name or service not known
Error connecting smt.docomo.ne.jp: [SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED] unsafe legacy renegotiation disabled (_ssl.c:1032)
Error connecting spmb.jatengprov.go.id: [Errno -3] Temporary failure in name resolution
400 good URLs so far...
Error connecting nregastrep.nic.in: [Errno 104] Connection reset by peer
Error connecting sso.acesso.gov.br: [Errno 104] Connection reset by peer
Error connecting videq.stream: [Errno -3] Temporary failure in name resolution
Error connecting viidey.co: [Errno 104] Connection reset by peer
450 good URLs so far...
500 good URLs so far...
Error connecting massarservice.men.gov.ma: [Errno 111] Connect call failed ('196.200.143.196', 443)
550 good URLs so far...
Error connecting unifiedportal-mem.epfindia.gov.in: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1032)
Error connecting 9moviesda.com: TimeoutError()
Error connecting amp.xnxx.com: TimeoutError()
Error connecting ara.xhamster.com: TimeoutError()
Error connecting auto.drom.ru: TimeoutError()
Error connecting bato.to: TimeoutError()
Error connecting de.xvideos.com: TimeoutError()
Error connecting divar.ir: TimeoutError()
Error connecting donya-e-eqtesad.com: TimeoutError()
Error connecting dzen.ru: TimeoutError()
Error connecting es.eporner.com: TimeoutError()
Error connecting ewaybillgst.gov.in: TimeoutError()
Error connecting fr.xvideos.com: TimeoutError()
Error connecting fra.xhamster.com: TimeoutError()
Error connecting id.woxh.world: TimeoutError()
Error connecting ifilo.net: TimeoutError()
Error connecting imgsrc.ru: TimeoutError()
Error connecting it.xvideos.com: TimeoutError()
Error connecting komiku.org: TimeoutError()
Error connecting liquipedia.net: TimeoutError()
Error connecting m.avito.ru: TimeoutError()
Error connecting m.ok.ru: TimeoutError()
Error connecting m.porno666.fo: TimeoutError()
Error connecting m.tabor.ru: TimeoutError()
Error connecting m.vk.com: TimeoutError()
Error connecting mail.ru: TimeoutError()
Error connecting mat6tube.com: TimeoutError()
Error connecting mm.anwap.today: TimeoutError()
Error connecting my.medu.ir: TimeoutError()
Error connecting my.xhcopy.life: TimeoutError()
Error connecting nickfinder.com: TimeoutError()
Error connecting pikabu.ru: TimeoutError()
Error connecting pmkisan.gov.in: TimeoutError()
Error connecting pt.eporner.com: TimeoutError()
Error connecting rutube.ru: TimeoutError()
Error connecting saednews.com: TimeoutError()
Error connecting ssc.gov.in: TimeoutError()
Error connecting thisvid.com: TimeoutError()
Error connecting uidai.gov.in: TimeoutError()
Error connecting uucms.karnataka.gov.in: TimeoutError()
Error connecting v.porno365.bike: TimeoutError()
Error connecting vegamovies.mk: TimeoutError()
Error connecting vegamovies.tz: TimeoutError()
Error connecting vi.xhspot.com: TimeoutError()
Error connecting woman.excite.co.jp: TimeoutError()
Error connecting wordwall.net: TimeoutError()
Error connecting workspace.google.com: TimeoutError()
Error connecting writexh.life: TimeoutError()
Error connecting wto.to: TimeoutError()
Error connecting www.ancestry.com: TimeoutError()
Error connecting www.aparat.com: TimeoutError()
Error connecting www.avito.ru: TimeoutError()
Error connecting www.bakecaincontrii.com: TimeoutError()
Error connecting www.banxia.la: TimeoutError()
Error connecting www.cmoa.jp: TimeoutError()
Error connecting www.cricbuzz.com: TimeoutError()
Error connecting www.curseforge.com: TimeoutError()
Error connecting www.epfindia.gov.in: TimeoutError()
Error connecting www.eporner.com: TimeoutError()
Error connecting www.espn.com: TimeoutError()
Error connecting www.espn.com.ve: TimeoutError()
Error connecting www.fanmtl.com: TimeoutError()
Error connecting www.fiverr.com: TimeoutError()
Error connecting www.flashscore.com: TimeoutError()
Error connecting www.flashscore.mobi: TimeoutError()
Error connecting www.fpo.xxx: TimeoutError()
Error connecting www.geny.com: TimeoutError()
Error connecting www.gismeteo.ru: TimeoutError()
Error connecting www.globo.com: TimeoutError()
Error connecting www.goal.com: TimeoutError()
Error connecting www.gob.mx: TimeoutError()
Error connecting www.goodreads.com: TimeoutError()
Error connecting www.goodreturns.in: TimeoutError()
Error connecting www.google.com: TimeoutError()
Error connecting www.google.com.hk: TimeoutError()
Error connecting www.gov.br: TimeoutError()
Error connecting www.gov.uk: TimeoutError()
Error connecting www.haberler.com: TimeoutError()
Error connecting www.hamshahrionline.ir: TimeoutError()
Error connecting www.hdtube.porn: TimeoutError()
Error connecting www.hepsiburada.com: TimeoutError()
Error connecting www.hibiny.ru: TimeoutError()
Error connecting www.hindustantimes.com: TimeoutError()
Error connecting www.hln.be: TimeoutError()
Error connecting www.hltv.org: TimeoutError()
Error connecting www.homedepot.com: TimeoutError()
Error connecting www.hotstar.com: TimeoutError()
Error connecting www.idealista.com: TimeoutError()
Error connecting www.idealista.it: TimeoutError()
Error connecting www.idnes.cz: TimeoutError()
Error connecting www.ign.com: TimeoutError()
Error connecting www.ikea.com: TimeoutError()
Error connecting www.ilmessaggero.it: TimeoutError()
Error connecting www.ilmeteo.it: TimeoutError()
Error connecting www.ilovepdf.com: TimeoutError()
Error connecting www.iltalehti.fi: TimeoutError()
Error connecting www.imagefap.com: TimeoutError()
Error connecting www.imdb.com: TimeoutError()
Error connecting www.indeed.com: TimeoutError()
Error connecting www.independent.co.uk: TimeoutError()
Error connecting www.index.hr: TimeoutError()
Error connecting www.indiansexstories3.com: TimeoutError()
Error connecting www.indiapost.gov.in: TimeoutError()
Error connecting www.infobae.com: TimeoutError()
Error connecting www.instagram.com: TimeoutError()
Error connecting www.interia.pl: TimeoutError()
Error connecting www.inven.co.kr: TimeoutError()
Error connecting www.ixl.com: TimeoutError()
Error connecting www.ixxx.com: TimeoutError()
Error connecting www.jagran.com: TimeoutError()
Error connecting www.jalan.net: TimeoutError()
Error connecting www.jaya9.bet: TimeoutError()
Error connecting www.joyclub.de: TimeoutError()
Error connecting www.jra.go.jp: TimeoutError()
Error connecting www.jusbrasil.com.br: TimeoutError()
Error connecting www.justdial.com: TimeoutError()
Error connecting www.jutarnji.hr: TimeoutError()
Error connecting www.jw.org: TimeoutError()
Error connecting www.kamababa.desi: TimeoutError()
Error connecting www.khabaronline.ir: TimeoutError()
Error connecting www.kleinanzeigen.de: TimeoutError()
Error connecting www.kohls.com: TimeoutError()
Error connecting www.kompas.com: TimeoutError()
Error connecting www.kooora.com: TimeoutError()
Error connecting www.ladepeche.fr: TimeoutError()
Error connecting www.lanacion.com.ar: TimeoutError()
Error connecting www.lavanguardia.com: TimeoutError()
Error connecting www.leboncoin.fr: TimeoutError()
Error connecting www.lecturas.com: TimeoutError()
Error connecting www.lefigaro.fr: TimeoutError()
Error connecting www.lemonde.fr: TimeoutError()
Error connecting www.leparisien.fr: TimeoutError()
Error connecting www.lequipe.fr: TimeoutError()
Error connecting www.leroymerlin.es: TimeoutError()
Error connecting www.leroymerlin.fr: TimeoutError()
Error connecting www.letras.mus.br: TimeoutError()
Error connecting www.linkedin.com: TimeoutError()
Error connecting www.livehindustan.com: TimeoutError()
Error connecting www.livescore.com: TimeoutError()
Error connecting www.lowes.com: TimeoutError()
Error connecting www.makemytrip.com: TimeoutError()
Error connecting www.mangago.me: TimeoutError()
Error connecting www.mangakakalot.gg: TimeoutError()
Error connecting www.manoramaonline.com: TimeoutError()
Error connecting www.marca.com: TimeoutError()
Error connecting www.marktplaats.nl: TimeoutError()
Error connecting www.mediaexpert.pl: TimeoutError()
Error connecting www.mediafire.com: TimeoutError()
Error connecting www.mercadolibre.com.ar: TimeoutError()
Error connecting www.mercadolibre.com.mx: TimeoutError()
Error connecting www.mercadolivre.com.br: TimeoutError()
Error connecting www.merkur.de: TimeoutError()
Error connecting www.meteociel.fr: TimeoutError()
Error connecting www.metropoles.com: TimeoutError()
Error connecting www.microsoft.com: TimeoutError()
Error connecting www.midilibre.fr: TimeoutError()
Error connecting www.mlb.com: TimeoutError()
Error connecting www.moneycontrol.com: TimeoutError()
Error connecting www.moviezwap.bike: TimeoutError()
Error connecting www.mp4moviez.blue: TimeoutError()
Error connecting www.mp4moviez.cv: TimeoutError()
Error connecting www.msn.com: TimeoutError()
Error connecting www.mundodeportivo.com: TimeoutError()
Error connecting www.myntra.com: TimeoutError()
Error connecting www.n-tv.de: TimeoutError()
Error connecting www.namasha.com: TimeoutError()
Error connecting www.national-lottery.co.uk: TimeoutError()
Error connecting www.natomanga.com: TimeoutError()
Error connecting www.naukri.com: TimeoutError()
Error connecting www.naver.com: TimeoutError()
Error connecting www.navitime.co.jp: TimeoutError()
Error connecting www.ndtv.com: TimeoutError()
Error connecting www.nesine.com: TimeoutError()
Error connecting www.netflix.com: TimeoutError()
Error connecting www.news.com.au: TimeoutError()
Error connecting www.newsweek.com: TimeoutError()
Error connecting www.nexusmods.com: TimeoutError()
Error connecting www.nike.com: TimeoutError()
Error connecting www.nikkansports.com: TimeoutError()
Error connecting www.nikkei.com: TimeoutError()
Error connecting www.ninisite.com: TimeoutError()
Error connecting www.njuskalo.hr: TimeoutError()
Error connecting www.novel543.com: TimeoutError()
Error connecting www.novinky.cz: TimeoutError()
Error connecting www.nu.nl: TimeoutError()
Error connecting www.nytimes.com: TimeoutError()
Error connecting www.ojogodobicho.com: TimeoutError()
Error connecting www.okbet.com: TimeoutError()
Error connecting www.olx.com.br: TimeoutError()
Error connecting www.onet.pl: TimeoutError()
Error connecting www.oolveri.com: TimeoutError()
Error connecting www.oricon.co.jp: TimeoutError()
Error connecting www.otomoto.pl: TimeoutError()
Error connecting www.otto.de: TimeoutError()
Error connecting www.ouest-france.fr: TimeoutError()
Error connecting www.ozon.ru: TimeoutError()
Error connecting www.patreon.com: TimeoutError()
Error connecting www.paypal.com: TimeoutError()
Error connecting www.pinterest.com: TimeoutError()
Error connecting www.pixiv.net: TimeoutError()
Error connecting www.playtime.com.ph: TimeoutError()
Error connecting www.porn300.com: TimeoutError()
Error connecting www.pornhat.com: TimeoutError()
Error connecting www.pornhub.com: TimeoutError()
Error connecting www.pornhub.org: TimeoutError()
Error connecting www.pornocarioca.com: TimeoutError()
Error connecting www.pornpics.com: TimeoutError()
Error connecting www.primevideo.com: TimeoutError()
Error connecting www.programme-tv.net: TimeoutError()
Error connecting www.prokerala.com: TimeoutError()
Error connecting www.promiedos.com.ar: TimeoutError()
Error connecting www.property24.com: TimeoutError()
Error connecting www.protothema.gr: TimeoutError()
Error connecting www.ptt.cc: TimeoutError()
Error connecting www.publi24.ro: TimeoutError()
Error connecting www.purepeople.com: TimeoutError()
Error connecting www.pussyboy.net: TimeoutError()
Error connecting www.pussyspace.com: TimeoutError()
Error connecting www.qorno.com: TimeoutError()
Error connecting www.quora.com: TimeoutError()
Error connecting www.reddit.com: TimeoutError()
Error connecting www.redfin.com: TimeoutError()
Error connecting www.redtube.com: TimeoutError()
Error connecting www.redwap.sex: TimeoutError()
Error connecting www.remove.bg: TimeoutError()
Error connecting www.repubblica.it: TimeoutError()
Error connecting www.researchgate.net: TimeoutError()
Error connecting www.rexporn.sex: TimeoutError()
Error connecting www.rightmove.co.uk: TimeoutError()
Error connecting www.roblox.com: TimeoutError()
Error connecting www.rojgarresult.com: TimeoutError()
Error connecting www.russianfood.com: TimeoutError()
Error connecting www.ryanair.com: TimeoutError()
Error connecting www.sahibinden.com: TimeoutError()
Error connecting www.sakshi.com: TimeoutError()
Error connecting www.samsung.com: TimeoutError()
Error connecting www.screener.in: TimeoutError()
Error connecting www.scribd.com: TimeoutError()
Error connecting www.serviporno.com: TimeoutError()
Error connecting www.sexvid.pro: TimeoutError()
Error connecting www.sexvid.xxx: TimeoutError()
Error connecting www.seznam.cz: TimeoutError()
Error connecting www.shaalaa.com: TimeoutError()
Error connecting www.shahrekhabar.com: TimeoutError()
Error connecting www.shiksha.com: TimeoutError()
Error connecting www.shutterstock.com: TimeoutError()
Error connecting www.sidrachain.com: TimeoutError()
Error connecting www.sofascore.com: TimeoutError()
Error connecting www.sondakika.com: TimeoutError()
Error connecting www.sozcu.com.tr: TimeoutError()
Error connecting www.speedtest.net: TimeoutError()
Error connecting www.spiegel.de: TimeoutError()
Error connecting www.sport.es: TimeoutError()
Error connecting www.sport.pl: TimeoutError()
Error connecting www.sportingbet.bet.br: TimeoutError()
Error connecting www.sportybet.com: TimeoutError()
Error connecting www.staseraintv.com: TimeoutError()
Error connecting www.storm.mg: TimeoutError()
Error connecting www.subito.it: TimeoutError()
Error connecting www.sugotoku.docomo.ne.jp: TimeoutError()
Error connecting www.superporn.com: TimeoutError()
Error connecting www.t-online.de: TimeoutError()
Error connecting www.tabnak.ir: TimeoutError()
Error connecting www.tagesschau.de: TimeoutError()
Error connecting www.taktube.net: TimeoutError()
Error connecting www.tamildhool.net: TimeoutError()
Error connecting www.target.com: TimeoutError()
Error connecting www.telegraph.co.uk: TimeoutError()
Error connecting www.temu.com: TimeoutError()
Error connecting www.terra.com.br: TimeoutError()
Error connecting www.tgju.org: TimeoutError()
Error connecting www.theguardian.com: TimeoutError()
Error connecting www.threads.com: TimeoutError()
Error connecting www.thscore.mobi: TimeoutError()
Error connecting www.tiktok.com: TimeoutError()
Error connecting www.tjk.org: TimeoutError()
Error connecting www.tnaflix.com: TimeoutError()
Error connecting www.tokyomotion.net: TimeoutError()
Error connecting www.tori.fi: TimeoutError()
Error connecting www.tradingview.com: TimeoutError()
Error connecting www.trendyol.com: TimeoutError()
Error connecting www.tripadvisor.com: TimeoutError()
Error connecting www.tuazar.com: TimeoutError()
Error connecting www.tudogostoso.com.br: TimeoutError()
Error connecting www.turkiye.gov.tr: TimeoutError()
Error connecting www.tvonenews.com: TimeoutError()
Error connecting www.twitch.tv: TimeoutError()
Error connecting www.twpornstars.com: TimeoutError()
Error connecting www.txnhh.com: TimeoutError()
Error connecting www.tycsports.com: TimeoutError()
Error connecting www.universal-credit.service.gov.uk: TimeoutError()
Error connecting www.uol.com.br: TimeoutError()
Error connecting www.ups.com: TimeoutError()
Error connecting www.upwork.com: TimeoutError()
Error connecting www.varzesh3.com: TimeoutError()
Error connecting www.vg.no: TimeoutError()
Error connecting www.w3schools.com: TimeoutError()
Error connecting www.walmart.com: TimeoutError()
Error connecting www.wannonce.com: TimeoutError()
Error connecting www.wattpad.com: TimeoutError()
Error connecting www.welt.de: TimeoutError()
Error connecting www.wetter.com: TimeoutError()
Error connecting www.whatsapp.com: TimeoutError()
Error connecting www.wildberries.ru: TimeoutError()
Error connecting www.wnacg.com: TimeoutError()
Error connecting www.wp.pl: TimeoutError()
Error connecting www.xbox.com: TimeoutError()
Error connecting www.xnxx-arabic.com: TimeoutError()
Error connecting www.xnxx.com: TimeoutError()
Error connecting www.xnxx.es: TimeoutError()
Error connecting www.xnxx.tv: TimeoutError()
Error connecting www.xnxx3.com: TimeoutError()
Error connecting www.xpaja.net: TimeoutError()
Error connecting www.xv-ru.com: TimeoutError()
Error connecting www.xvideos-ar.com: TimeoutError()
Error connecting www.xvideos.com: TimeoutError()
Error connecting www.xvideos.es: TimeoutError()
Error connecting www.xvideos2.com: TimeoutError()
Error connecting www.xvv1deos.com: TimeoutError()
Error connecting www.xxxhindi.to: TimeoutError()
Error connecting www.yahoo.co.jp: TimeoutError()
Error connecting www.yahoo.com: TimeoutError()
Error connecting www.yako.gg: TimeoutError()
Error connecting www.yallakora.com: TimeoutError()
Error connecting www.ynet.co.il: TimeoutError()
Error connecting www.youjizz.com: TimeoutError()
Error connecting www.youporn.com: TimeoutError()
Error connecting www.youtube.com: TimeoutError()
Error connecting www.zalando.de: TimeoutError()
Error connecting www.zillow.com: TimeoutError()
Error connecting www.zona-interactiva.canalrcn.com: TimeoutError()
Error connecting www1.123av.com: TimeoutError()
Error connecting www2.hm.com: TimeoutError()
Error connecting www3.nhk.or.jp: TimeoutError()
Error connecting x.com: TimeoutError()
Error connecting x.ijavhd.com: TimeoutError()
Error connecting x.sex-studentki.co: TimeoutError()
Error connecting xbato.com: TimeoutError()
Error connecting xhaccess.com: TimeoutError()
Error connecting xhamster.best: TimeoutError()
Error connecting xhamster.com: TimeoutError()
Error connecting xhamster.desi: TimeoutError()
Error connecting xhamster1.desi: TimeoutError()
Error connecting xhamster19.com: TimeoutError()
Error connecting xhamster2.com: TimeoutError()
Error connecting xhamster43.desi: TimeoutError()
Error connecting xhcopy.life: TimeoutError()
Error connecting xhopen.com: TimeoutError()
Error connecting xhtube.life: TimeoutError()
Error connecting xhwide5.com: TimeoutError()
Error connecting xn--3-5wfa4ehe3i1bd1ood.com: TimeoutError()
Error connecting xn--42c5ab1a9aq9hqb5dud.com: TimeoutError()
Error connecting xn--72cz9dvb1cxc.net: TimeoutError()
Error connecting xn--l3cg7a8a0cwa3f.com: TimeoutError()
Error connecting xnhau.sh: TimeoutError()
Error connecting xnxx.com.se: TimeoutError()
Error connecting xnxx.health: TimeoutError()
Error connecting xnxxvideos.info: TimeoutError()
Error connecting xoso.com.vn: TimeoutError()

In [8]:
data = []
good_streams = set()
skipped_packets = 0


def process_server_hello(packet):
    good_streams.add(packet.tcp.stream)


def process_client_hello(packet):
    if packet.tcp.stream not in good_streams:
        global skipped_packets
        skipped_packets += 1
        return
    if not hasattr(packet.tls, "handshake_extensions_server_name"):
        print(f"Skipping packet without SNI")
        return
    data.append(
        {
            "timestamp": packet.sniff_time,
            "domain": packet.tls.handshake_extensions_server_name,
        }
    )


# We only want TLS Client Hello packets, but we want to skip streams for which the TLS
# handshake never concluded
cap_server_hello = pyshark.FileCapture(PCAP_FILE, display_filter="tls.handshake.type == 2")
await cap_server_hello.packets_from_tshark(process_server_hello)

print(f"Found {len(good_streams)} streams with Server Hello packets.")

cap_client_hello = pyshark.FileCapture(PCAP_FILE, display_filter="tls.handshake.type == 1")
await cap_client_hello.packets_from_tshark(process_client_hello)

print(f"{len(data)} TLS streams found. Skipped {skipped_packets} streams that never completed the handshake.")

Found 840 streams with Server Hello packets.
925 TLS streams found. Skipped 939 streams that never completed the handshake.

In [ ]:
data = pd.DataFrame(data)
# Express timestamps as second offset since the first packet
initial_time = data["timestamp"].min()
data["timestamp"] = (data["timestamp"] - initial_time).dt.total_seconds()
data

In [6]:
mapping = {}

good_urls = good_urls.sample(frac=1).reset_index(drop=True)
index = 0
for domain in data["domain"].unique():
    mapping[domain] = good_urls["url"].iloc[index]
    index += 1
    if index >= len(good_urls):
        index = 0

data_mapped = data.copy()
data_mapped["url"] = data_mapped["domain"].map(mapping)
data_mapped = data_mapped.drop(columns=["domain"])
data_mapped

        timestamp                                   url
0        0.000000                    https://yandex.com
1        3.478341               https://ma.afribaba.com
2        8.119483          https://www.espncricinfo.com
3        9.129903                https://www.joyclub.de
4        9.481431                https://www.joyclub.de
..            ...                                   ...
920  14276.638800              https://www.haberler.com
921  14276.639166              https://www.haberler.com
922  14276.645345  https://articulo.mercadolibre.com.ar
923  14277.118654              https://www.haberler.com
924  14277.422471              https://www.haberler.com

[925 rows x 2 columns]

In [7]:
BUCKET_SIZE = 30 * 60  # 30 mins

data_grouped = data_mapped
data_grouped["group"] = (data_grouped["timestamp"] // BUCKET_SIZE).astype(int)
data_grouped.iloc[np.r_[0:5, -5:0]]

        timestamp                                   url  group
0        0.000000                    https://yandex.com      0
1        3.478341               https://ma.afribaba.com      0
2        8.119483          https://www.espncricinfo.com      0
3        9.129903                https://www.joyclub.de      0
4        9.481431                https://www.joyclub.de      0
920  14276.638800              https://www.haberler.com      7
921  14276.639166              https://www.haberler.com      7
922  14276.645345  https://articulo.mercadolibre.com.ar      7
923  14277.118654              https://www.haberler.com      7
924  14277.422471              https://www.haberler.com      7

In [9]:
BUCKETS_TO_KEEP = 3

# we will keep the most populous buckets
group_sizes = data_grouped.groupby("group").size()
data_pruned = data_grouped[
    data_grouped["group"].isin(group_sizes.nlargest(BUCKETS_TO_KEEP).index.tolist())
]
print(f"Largest bucket has {data_pruned.groupby('group').size().max()} packets")
print(f"Smallest bucket has {data_pruned.groupby('group').size().min()} packets")
data_pruned

Largest bucket has 338 packets
Smallest bucket has 190 packets

       timestamp                                  url  group
0       0.000000                   https://yandex.com      0
1       3.478341              https://ma.afribaba.com      0
2       8.119483         https://www.espncricinfo.com      0
3       9.129903               https://www.joyclub.de      0
4       9.481431               https://www.joyclub.de      0
..           ...                                  ...    ...
778  8814.500210           https://www.tamildhool.net      4
779  8815.311921        https://www.flightradar24.com      4
780  8816.035217  https://xn--42c5ab1a9aq9hqb5dud.com      4
781  8816.568212  https://xn--42c5ab1a9aq9hqb5dud.com      4
782  8817.367987             https://ge.xhamster.desi      4

[782 rows x 3 columns]

In [10]:
data_pruned.rename(columns={"group": "trace"}).to_csv(OUTPUT_FILE, index=False)

In [12]:
def remap_trace_index(traces):
    mapping = {}
    for i, trace_id in enumerate(traces["trace"].unique()):
        mapping[trace_id] = i
    traces["trace"] = traces["trace"].map(mapping)

def combine_traces(trace_file_1, trace_file_2):
    trace_1 = pd.read_csv(trace_file_1)
    remap_trace_index(trace_1)
    trace_2 = pd.read_csv(trace_file_2)
    remap_trace_index(trace_2)
    offset = trace_1["trace"].max() + 1
    trace_2["trace"] += offset
    return pd.concat([trace_1, trace_2], ignore_index=True)

In [17]:
traces = pd.read_csv("output/combined.csv")
for trace in traces["trace"].unique():
    mask = traces["trace"] == trace
    traces.loc[mask, "timestamp"] -= traces.loc[mask, "timestamp"].min()

traces.to_csv("output/combined.csv", index=False)